### PR TITLE
split % and # while tokenizing

### PR DESCRIPTION
**Pull request by forslund**
Handles things like 75% and "this is pr #61"

`75%` -> `75 %`
`#61` -> `# 61`
`hashtag #1world` will still be `hashtag #1world`

### CODE REVIEW

**Comment by JarbasAl** [comment]
i like the way you handled this, maybe also add some tests to the tokenize method specifically?

**Comment by forslund** [comment]
Absolutely, will push that later (probably tomorrow)

**Comment by forslund** [comment]
Updated with some basic tests of the tokenize function.

**Comment by JarbasAl** [comment]
looks great, we need to add those to portuguese normalizer (overrides tokenize), want to do it? otherwise i can do it in a follow up PR

**Comment by forslund** [comment]
I'll leave it to you in a followup PR, I wouldn't know how to write a testcase in Portuguese :)

**Comment by JarbasAl** [comment]
the only extra in portuguese is splitting at "-", so "amo-te" becomes ["amo", "te"]

This particular example means "i love you", so its equivalent of splitting it into ["love", "you"]

i can do a follow up PR, but i'm no good with regex so i'm sure you would do it better :p

**Comment by forslund** [comment]
I'll add that and you can write a couple of test cases for it maybe?

**Comment by forslund** [comment]
The PT one is also handled now. Since no new comments I'll merge this now.

**Pull request merged**
