### PR TITLE
Add extract_duration for french

### PR DESCRIPTION
**Pull request by bboutier**
Add extract_duration support for french language (inspired from what was done for german).

#### Type of PR
- [ ] Bugfix
- [x] Feature implementation
- [ ] Refactor of code (without functional changes)
- [ ] Documentation improvements
- [ ] Test improvements

#### Testing
Unit tests added under ` test/test_parse_fr.py`

### CODE REVIEW

**Comment by devs-mycroft** [comment]
Hello, @bboutier, thank you for helping with the Mycroft project! We welcome everyone
into the community and greatly appreciate your help as we work to build an AI
for Everyone.

To protect yourself, the project, and users of Mycroft technologies we require
a Contributor Licensing Agreement (CLA) before accepting any code
contribution. This agreement makes it crystal clear that along with your
code you are offering a license to use it within the confines of this project.
You retain ownership of the code, this is just a license.

Please visit https://mycroft.ai/cla to initiate this one-time signing. Thank
you!

**Comment by bboutier** [comment]
> Hello, @bboutier, thank you for helping with the Mycroft project! We welcome everyone
> into the community and greatly appreciate your help as we work to build an AI
> for Everyone.
> 
> To protect yourself, the project, and users of Mycroft technologies we require
> a Contributor Licensing Agreement (CLA) before accepting any code
> contribution. This agreement makes it crystal clear that along with your
> code you are offering a license to use it within the confines of this project.
> You retain ownership of the code, this is just a license.
> 
> Please visit https://mycroft.ai/cla to initiate this one-time signing. Thank
> you!

I've just done it, using same email as the one i use on github, i let you check :)

**Comment by ChanceNCounter** [comment]
Hi! You can ignore that failing Py3.5 test. We broke it in a recent PR (another PR is pending to drop 3.5 support.)

This repo has a pretty small team. @krisgesling is the Mycroft employee around here, and he'll have to follow up on the CLA. May or may not see him on weekends.

As for the code, somebody will take a closer look ASAP (sometimes that means later today and sometimes it's next week =P) At first glance, it looks like you did the API right, so there's that.

Thanks for helping!

**Comment by JarbasAl** [comment]
at first sight this looks good, but i wonder if we should get the normalize method in there before merging this so number words are replaced properly and all unittests pass?

i realize this one might be non trivial for french, since things like quatre-vingt-dix-huit will be harder to parse than in most languages, 90 8 is just a sum, 4 20 10 8 is way harder

**Comment by krisgesling** [comment]
CLA received - thanks for the great contribution @bboutier!

**Comment by bboutier** [comment]
> at first sight this looks good, but i wonder if we should get the normalize method in there before merging this so number words are replaced properly and all unittests pass?
> 
> i realize this one might be non trivial for french, since things like quatre-vingt-dix-huit will be harder to parse than in most languages, 90 8 is just a sum, 4 20 10 8 is way harder

Yep, thanks for the tip, i was not aware of this `normalize` function so i have updated my PR to now support simple translations from words to number.
Not sure i will get time to go deeper with supporting more complex french (such as fraction like "et demi") even if i've just saw the `extract_number_fr` function which seems to have already implemtened a part of what will be required to do it.

**Comment by JarbasAl** [comment]
looks good to me, further updates should go into the other functions in different PRs :+1:

if @ChanceNCounter approves i think this can go in before release 0.4?

**Comment by ChanceNCounter** [comment]
I'm juggling, so I defer to your approval. Go for it!

---

For what it's worth, and I have no idea how well it translates to a particular language, the epiphany I had in English that seems to have stuck was this:

In English, you can parse a multi-word number from left to right, pausing your sum each time you encounter a number that constitutes a "group" (though I think we've only accounted for powers of ten so far, in English.) You set the sum aside if the power of ten is the largest *remaining* power of ten in the string.

For example, in the phrase, "one million two hundred seventy five thousand one hundred nineteen", you would sum:

"one million" (pause) ... # million is the largest remaining power of ten
set aside 1,000,000
"two hundred" # hundred is not the largest remaining power of ten
"two hundred seventy five thousand" # thousand is the largest remaining power of ten
set aside 275,000
"one hundred" # hundred is the largest remaining string
set aside 100
"nineteen" # end string
sum: 1,000,000 + 275,000 + 100 + 19
result: 1,275,119

**Pull request merged**
