### PR TITLE
implement farsi support

### PR DESCRIPTION
**Pull request by ChanceNCounter**
This is a rebase of @HKalbasi's Farsi PR, #171, which was supposed to be merged directly, but instead, it was how I discovered that my PR extension has the "comment" and "close with comment" buttons switched, and furthermore that force-pushing a PR branch makes it impossible to reopen the PR until the PR gets another commit.

*Whew*.

If @HKalbasi turns up in the next few days, I'd rather reopen his PR than merge this one. But, if not, here's one we can merge. The code's already been reviewed, I just borked the force-push after a rebase.

### CODE REVIEW

**Comment by HKalbasi** [comment]
That's OK. Just merge it. :)

**Comment by ChanceNCounter** [comment]
You got it!

**Comment by krisgesling** [comment]
:tada: :tada: :tada: 
Awesome, thanks so much for all your work on this @HKalbasi!!

As an aside - we'll release a new version of Lingua Franca so that Mycroft users and other projects can use Farsi, and we've been naming each release "Hello world" in a relevant language each time. How would you say "Hello world" in Farsi?

**Comment by HKalbasi** [comment]
:tada: :tada: :tada: 
"Hello world" in farsi is "سلام دنیا" or "salaam donya"

**Comment by ChanceNCounter** [comment]
Indeed, there's already a draft release by that name ready to go :)

**Comment by krisgesling** [comment]
Yeah great, do you think Github will crack it if we include the Perso-Arabic script? Maybe:
> سلام دنیا (Salaam Donya)

**Comment by ChanceNCounter** [comment]
Yes, it worked!

**Pull request merged**
