### PR TITLE
In italian hour is ora

### PR DESCRIPTION
**Pull request by Stypox**
not hora

#### Type of PR
If your PR fits more than one category, there is a high chance you should submit more than one PR. Please consider this carefully before opening the PR.
_Either delete those that do not apply, or add an x between the square brackets like so: `- [x]`_
- [x] Bugfix
- [ ] Feature implementation
- [ ] Refactor of code (without functional changes)
- [ ] Documentation improvements
- [ ] Test improvements

### CODE REVIEW

**Comment by devs-mycroft** [comment]
Hello, @Stypox, thank you for helping with the Mycroft project! We welcome everyone
into the community and greatly appreciate your help as we work to build an AI
for Everyone.

To protect yourself, the project, and users of Mycroft technologies we require
a Contributor Licensing Agreement (CLA) before accepting any code
contribution. This agreement makes it crystal clear that along with your
code you are offering a license to use it within the confines of this project.
You retain ownership of the code, this is just a license.

Please visit https://mycroft.ai/cla to initiate this one-time signing. Thank
you!

**Review by ChanceNCounter — APPROVED** [review]
Yes, it sure seems to be! Approved, pending CLA.

**Comment by Stypox** [comment]
I submit the CLA [here](https://mycroft.ai/cla) but still haven't received any mail. Btw I am not planning to become a contibutor, I am just chipping in to fix two small translations.

**Comment by ChanceNCounter** [comment]
Paging @krisgesling (Mycroft employee, I'm an outside maintainer) to look into the CLA situation.

Don't sweat the word "contributor." It just means you did work on the project. Modern copyright law, especially in America, is a minefield. The CLA makes it a moot point.

**Comment by krisgesling** [comment]
Hey @Stypox I haven't seen it come through so I've just tried emailing the address associated with this github account. If that doesn't work can you email me direct at kris.gesling@our.domain and we can get this fixed up.

Whilst small contributions may not meet the standards required to be a unique and significant contribution, determining which changes do meet that standard can be a messy grey area. Having every contribution large or small covered by a CLA makes it much simpler.

**Comment by Stypox** [comment]
I've done the CLA

**Comment by Stypox** [comment]
There are no tests related to this change, since there is no `TestNiceDateFormat` class in `test_format_it.py`. Should I add it, even though it would mean adding a bunch of other (possibly failing) tests unrelated to this simple change?

**Comment by krisgesling** [comment]
Thanks Fabio, 

Happy to merge this as is. Though we always welcome better test coverage if you wanted to do a follow up PR :)

**Pull request merged**
